def raise_exception():
        x = 4
        y = "raiseexception"
        result = x + y
    
    raise_exception()